# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build image
  jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'rolando999/aspnet-mssql'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

- stage: ScriptBaschPrint
  displayName: ScriptBasch
  jobs:
  - job: ScriptBasch
    displayName: 'Script Basch write Hello Word'
    strategy:
      parallel: 10
    steps:
      - script: echo "Hola Mundo"
        displayName: 'Imprimir Hola Mundo'

  - job: ScriptBaschFiles
    displayName: 'Script Basch Create and Print Files'
    steps:
      - script: |
              for i in {1..10}
              do
                filename="file_$i.txt"
                date > $filename
              done
              cat $filename